server:
  port: 8081
  context-path: /api
  tomcat:
    max-threads: 2000

spring:
    http:
      multipart.maxFileSize: 100Mb
      maxRequestSize: 1000Mb
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    datasource:
        url: jdbc:mysql://192.168.2.200:3306/bpm?useUnicode=true&characterEncoding=utf8
        username: root
        password: Touch-Spring.com
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:dao/*.xml
  typeAliasesPackage: com.magicears.bpm.dao


system:
  filePath: D:\\project\\bpm\\api/data